spring:
  profiles:
    active: dev

  application:
    name: fly-drop

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Aphler3294@
    url: jdbc:mysql://47.97.10.192:4923/fly_drop?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true

#  data:
#    redis:
#      host: 47.97.10.192
#      port: 6379
#      password: Aphler3294@
#      connect-timeout: 50000ms


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: aphler.ossServer.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
